# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(670, 371)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QtCore.QSize(670, 371))
        Main.setMaximumSize(QtCore.QSize(670, 371))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../daetsam-beca-15-16/source/_static/daetsam_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        Main.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Spain))
        Main.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(Main)
        self.centralWidget.setObjectName("centralWidget")
        self.tabMain = QtWidgets.QTabWidget(self.centralWidget)
        self.tabMain.setGeometry(QtCore.QRect(10, 10, 651, 291))
        self.tabMain.setObjectName("tabMain")
        self.tabWifi = QtWidgets.QWidget()
        self.tabWifi.setObjectName("tabWifi")
        self.tableWiFi = QtWidgets.QTableWidget(self.tabWifi)
        self.tableWiFi.setGeometry(QtCore.QRect(10, 10, 481, 221))
        self.tableWiFi.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWiFi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWiFi.setProperty("showDropIndicator", False)
        self.tableWiFi.setDragDropOverwriteMode(False)
        self.tableWiFi.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWiFi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWiFi.setObjectName("tableWiFi")
        self.tableWiFi.setColumnCount(0)
        self.tableWiFi.setRowCount(0)
        self.btnAccesos = QtWidgets.QPushButton(self.tabWifi)
        self.btnAccesos.setGeometry(QtCore.QRect(10, 230, 171, 22))
        self.btnAccesos.setObjectName("btnAccesos")
        self.btnDenegados = QtWidgets.QPushButton(self.tabWifi)
        self.btnDenegados.setGeometry(QtCore.QRect(180, 230, 171, 22))
        self.btnDenegados.setObjectName("btnDenegados")
        self.btnErrores = QtWidgets.QPushButton(self.tabWifi)
        self.btnErrores.setGeometry(QtCore.QRect(350, 230, 141, 22))
        self.btnErrores.setObjectName("btnErrores")
        self.btnAbrirLogs = QtWidgets.QPushButton(self.tabWifi)
        self.btnAbrirLogs.setGeometry(QtCore.QRect(500, 180, 141, 71))
        self.btnAbrirLogs.setObjectName("btnAbrirLogs")
        self.tabMain.addTab(self.tabWifi, "")
        self.tabEquipos = QtWidgets.QWidget()
        self.tabEquipos.setObjectName("tabEquipos")
        self.btnEquiposOnline = QtWidgets.QPushButton(self.tabEquipos)
        self.btnEquiposOnline.setGeometry(QtCore.QRect(10, 230, 141, 22))
        self.btnEquiposOnline.setObjectName("btnEquiposOnline")
        self.tableEquipos = QtWidgets.QTableWidget(self.tabEquipos)
        self.tableEquipos.setGeometry(QtCore.QRect(10, 10, 481, 221))
        self.tableEquipos.setObjectName("tableEquipos")
        self.tableEquipos.setColumnCount(0)
        self.tableEquipos.setRowCount(0)
        self.btnEquiposOffline = QtWidgets.QPushButton(self.tabEquipos)
        self.btnEquiposOffline.setGeometry(QtCore.QRect(150, 230, 141, 22))
        self.btnEquiposOffline.setObjectName("btnEquiposOffline")
        self.tabMain.addTab(self.tabEquipos, "")
        self.tabServicios = QtWidgets.QWidget()
        self.tabServicios.setObjectName("tabServicios")
        self.tabMain.addTab(self.tabServicios, "")
        self.tabConfiguracion = QtWidgets.QWidget()
        self.tabConfiguracion.setObjectName("tabConfiguracion")
        self.tabMain.addTab(self.tabConfiguracion, "")
        Main.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 670, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        Main.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Main)
        self.mainToolBar.setObjectName("mainToolBar")
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Main)
        self.statusBar.setObjectName("statusBar")
        Main.setStatusBar(self.statusBar)
        self.actionSalir = QtWidgets.QAction(Main)
        self.actionSalir.setObjectName("actionSalir")
        self.menuMenu.addAction(self.actionSalir)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(Main)
        self.tabMain.setCurrentIndex(0)
        self.actionSalir.triggered.connect(Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Gestion IT DAETSAM"))
        self.tableWiFi.setSortingEnabled(True)
        self.btnAccesos.setText(_translate("Main", "Ver Accesos Autorizados"))
        self.btnDenegados.setText(_translate("Main", "Ver Accesos Denegados"))
        self.btnErrores.setText(_translate("Main", "Ver Errores"))
        self.btnAbrirLogs.setText(_translate("Main", "Abrir archivo de logs"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabWifi), _translate("Main", "WiFi"))
        self.btnEquiposOnline.setText(_translate("Main", "Ver Equipos Online"))
        self.btnEquiposOffline.setText(_translate("Main", "Ver Equipos Offline"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabEquipos), _translate("Main", "Equipos"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabServicios), _translate("Main", "Servicios"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabConfiguracion), _translate("Main", "Configuracion"))
        self.menuMenu.setTitle(_translate("Main", "Menu"))
        self.actionSalir.setText(_translate("Main", "Salir"))

